baseURL = "https://canadadev.com"
languageCode = "en-ca"
title = "CanadaDev"
theme = "bexar-hugo"
summaryLength = "10"
paginate = 6

[outputs]
  home = ["HTML", "AMP", "RSS", "JSON"]
  page = ["HTML"]

[params.quickContact]
  enable = true
  
# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  URL = "plugins/slick/slick.css"
  [[params.plugins.css]]
  URL = "plugins/fontawesome/font-awesome.min.css"
  [[params.plugins.css]]
  URL = "plugins/animate/animate.css"
  [[params.plugins.css]]
  URL = "plugins/venobox/venobox.css"
  [[params.plugins.css]]
  URL = "plugins/magnific-popup/magnific-popup.css"
  [[params.plugins.css]]
  URL = "plugins/themify-icons/themify-icons.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  URL = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "plugins/slick/slick.min.js"
  [[params.plugins.js]]
  URL = "plugins/google-map/gmap.js"
  [[params.plugins.js]]
  URL = "plugins/venobox/venobox.min.js"
  [[params.plugins.js]]
  URL = "plugins/modernizer/modernizr.min.js"
  [[params.plugins.js]]
  URL = "plugins/filterizr/jquery.filterizr.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/fuse.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/mark.js"
  [[params.plugins.js]]
  URL = "plugins/search/search.js"
  [[params.plugins.js]]
  URL = "plugins/slick/slick.min.js"
  [[params.plugins.js]]
  URL = "plugins/match-height/jquery.matchHeight-min.js"
  [[params.plugins.js]]
  URL = "plugins/shuffle/shuffle.min.js"
  [[params.plugins.js]]
  URL = "plugins/magnific-popup/jquery.magnific.popup.min.js"

# navigation
[menu]

  [[menu.main]]
  name = "Benefits"
  URL = "/benefits"
  weight = 1
  
  [[menu.main]]
  name = "Chapters"
  URL = "/meetup"
  weight = 2

  [[menu.main]]
  name = "Jobs"
  URL = "/jobs"
  weight = 3

  [[menu.main]]
  name = "About"
  weight = 4
  hasChildren = true

    [[menu.main]]
    parent = "About"
    name = "Association"
    URL = "/about"
    weight = 1

    [[menu.main]]
    parent = "About"
    name = "Sponsors"
    URL = "/sponsors"
    weight = 2

    [[menu.main]]
    parent = "About"
    name = "Code of Ethics"
    URL = "/ethics"
    weight = 3

    [[menu.main]]
    parent = "About"
    name = "Become a Chapter Leader"
    URL = "/organize"
    weight = 4

  [[menu.footer]]
  name = "Terms of Service"
  URL = "/terms"
  weight = 6
  
  [[menu.footer]]
  name = "Privacy Policy"
  URL = "/privacy"
  weight = 7

  [[menu.footer]]
  name = "Code of Conduct"
  URL = "/conduct"
  weight = 8

[params]
logo = "images/canadadev.png"
logoAlt = "images/canadadev-alt.png"
home = "Home"
# Meta data
description = "CanadaDev is the professional association of software engineers in Canada"
author = "Bevan Hunt"
# google map
gmapAPI = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
mapLatitude = "51.5223477"
mapLongitude = "-0.1622023"
mapMarker = "images/marker.png"
# Google Analitycs
googleAnalitycsID = "UA-148418498-1"
# mailchimp subsciption
mailchimpFormAction = "https://themefisher.us9.list-manage.com/subscribe/post?u=f95ece2732a6e9925f2e70a61&amp;id=b1e227529e" # replace this url with yours
mailchimpFormName = "b_f95ece2732a6e9925f2e70a61_b1e227529e" # replace this code with yours

  # Preloader
  [params.preloader]
  enable = true

  # top header
  [params.topHeader]
  enable = false
  email = ""
  phone = ""
    # social icon
    [[params.topHeader.icon]]
      icon = "fa-meetup"
      URL = "/meetup"
    [[params.topHeader.icon]]
      icon = "fa-linkedin"
      URL = "/linkedin"
    [[params.topHeader.icon]]
      icon = "fa-vimeo"
      URL = "/vimeo"

  # search
  [params.search]
  enable = false

  # Navigation get start button
  [params.navBtn]
  enable = false
  btnText = "Join Now"
  URL = "/join"

  # call to action
  [params.cta]
  enable = true
  title = "Are you a company that wants to meet software engineers?"
  bgImage = "images/backgrounds/cta-lg.webp"
  bgImageAlt = "images/backgrounds/cta-lg.jpg"
  btnText = "Become a Sponsor"
  URL = "https://canadadev.memberful.com/checkout?plan=42787"

  # Footer
  [params.footer]
  enable = false
  content = "CanadaDev is the professional association of software engineers in Canada. CanadaDev provides meetups, networking, mentorship, advocacy, lobbying, leading edge content, employment opportunities, and discounts. We take our members to the next level!"

    # follow us on social site
    [params.footer.followUs]
    title = "Follow Us On"

      [[params.footer.followUs.socialIcon]]
      icon = "fa-meetup"
      URL = "/meetup"

      [[params.footer.followUs.socialIcon]]
      icon = "fa-linkedin"
      URL = "/linkedin"

      [[params.footer.followUs.socialIcon]]
      icon = "fa-vimeo"
      URL = "/vimeo"

    # Contact
    [params.footer.contact]
    title = "Contact Us"

      [[params.footer.contact.contactList]]
      listItem = "1383 W 8th Ave, Vancouver, BC V6H 3V9"

      [[params.footer.contact.contactList]]
      listItem = "1-647-560-2338 (CDEV)"

      [[params.footer.contact.contactList]]
      listItem = "hello@canadadev.com"

  # newsletter
  [params.newsletter]
  enable = false
  title = "Subscribe Newsletter"

  # copyright
  [params.copyright]
  copyright = "A hugo theme by themefisher.com"