baseURL = "https://dispatcher.dev"
languageCode = "en-ca"
title = "Dispatcher - Unifies the Supply Chain"
theme = "bexar-hugo"
summaryLength = "10"
paginate = 6

[outputs]
  home = ["HTML", "AMP", "RSS", "JSON"]
  page = ["HTML"]

[params.quickContact]
  enable = true
  
# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  URL = "plugins/slick/slick.css"
  [[params.plugins.css]]
  URL = "plugins/fontawesome/font-awesome.min.css"
  [[params.plugins.css]]
  URL = "plugins/animate/animate.css"
  [[params.plugins.css]]
  URL = "plugins/venobox/venobox.css"
  [[params.plugins.css]]
  URL = "plugins/magnific-popup/magnific-popup.css"
  [[params.plugins.css]]
  URL = "plugins/themify-icons/themify-icons.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  URL = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "plugins/slick/slick.min.js"
  [[params.plugins.js]]
  URL = "plugins/google-map/gmap.js"
  [[params.plugins.js]]
  URL = "plugins/venobox/venobox.min.js"
  [[params.plugins.js]]
  URL = "plugins/modernizer/modernizr.min.js"
  [[params.plugins.js]]
  URL = "plugins/filterizr/jquery.filterizr.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/fuse.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/mark.js"
  [[params.plugins.js]]
  URL = "plugins/search/search.js"
  [[params.plugins.js]]
  URL = "plugins/slick/slick.min.js"
  [[params.plugins.js]]
  URL = "plugins/match-height/jquery.matchHeight-min.js"
  [[params.plugins.js]]
  URL = "plugins/shuffle/shuffle.min.js"
  [[params.plugins.js]]
  URL = "plugins/magnific-popup/jquery.magnific.popup.min.js"

# navigation
[menu]
  
  [[menu.main]]
  name = "Supply Chain Solution"
  URL = "/products/supplychain"
  weight = 1

  [[menu.footer]]
  name = "Terms of Service"
  URL = "/terms"
  weight = 7
  
  [[menu.footer]]
  name = "Privacy Policy"
  URL = "/privacy"
  weight = 8

[params]
logo = "images/apibillme.svg"
logoAlt = "images/apibillme.svg"
home = "Home"
  # Preloader
  [params.preloader]
  enable = true

  # top header
  [params.topHeader]
  enable = false
  email = ""
  phone = ""
    # social icon
    [[params.topHeader.icon]]
      icon = "fab fa-linkedin-in"
      URL = "https://www.linkedin.com/company/18775532/"

  # search
  [params.search]
  enable = false

  # Navigation get start button
  [params.navBtn]
  enable = false
  btnText = "Join Now"
  URL = ""

  # call to action
  [params.cta]
  enable = false
  title = "Want an invite to the private beta?"
  bgImage = "images/backgrounds/cta-lg.webp"
  bgImageAlt = "images/backgrounds/cta-lg.jpg"
  btnText = "Signup Now"
  URL = ""

  [params.features]
  enable = true

  # Footer
  [params.footer]
  enable = true
  content = "Dispatcher provides a marketplace that unifies the supply chain. It is the best supply chain management platform."

    # follow us on social site
    [params.footer.followUs]
    title = "Follow Us On"

      [[params.footer.followUs.socialIcon]]
      icon = "fab fa-linkedin-in"
      URL = "https://www.linkedin.com/company/18775532/"

  # newsletter
  [params.newsletter]
  enable = false
  title = "Subscribe Newsletter"

  # copyright
  [params.copyright]
  copyright = "A hugo theme by themefisher.com"