---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: content/conduct
  label: Conduct
  create: all
  match: "**/*"
- type: directory
  path: content/sponsor
  label: Sponsor
  create: all
  match: "**/*"
- type: directory
  path: content/privacy
  label: Privacy
  create: all
  match: "**/*"
- type: directory
  path: content/team
  label: Team
  create: all
  match: "**/*"
- type: directory
  path: content/ethics
  label: Ethics
  create: all
  match: "**/*"
- type: directory
  path: content/jobs
  label: Jobs
  create: all
  match: "**/*"
- type: directory
  path: content/founders
  label: Founders
  create: all
  match: "**/*"
- type: directory
  path: content/terms
  label: Terms
  create: all
  match: "**/*"
- type: directory
  path: content/benefits
  label: Benefits
  create: all
  match: "**/*"
- type: directory
  path: content/about
  label: About
  create: all
  match: "**/*"
- type: directory
  path: content/search
  label: Search
  create: all
  match: "**/*"
- type: directory
  path: content/career
  label: Career
  create: all
  match: "**/*"
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.58.2
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.58.2
